env:
  browser: true
  es2021: true
  jest/globals: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
rules: {
  'import/prefer-default-export': 0,
  'import/extensions': 0,
  'class-methods-use-this': 0,
  'import/no-unresolved': 0,
  'react/function-component-definition': 0,
  'react/jsx-filename-extension': 0,
}
