play {
  modules.enabled += "play.api.db.DBModule"
  modules.enabled += "scalikejdbc.PlayDBApiAdapterModule"
  modules.enabled += "org.flywaydb.play.PlayModule"

  filters {
    hosts {
      allowed = [
        "."
      ]
    }
  }
  http {
    session.domain = null
  }
}

db.default {
  driver = "org.postgresql.Driver"
  url = "postgres://hemea:hemea@localhost:5432/hemea"
  poolMaxSize=30
  migration {
    auto = true
    initOnMigrate = true
    table = "schema_version" # Default is 'flyway_schema_history' from Flyway 5.0.0
  }
}