env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - jest
rules: {
  'import/prefer-default-export': 0,
  'import/extensions': 0,
  'class-methods-use-this': 0,
  'import/no-unresolved': 0
}
